appconfig:
  max_retries: 5
  max_recorders: 2
  port: 9999
  pnm_recording_location: './recordings'
  epiphan_recording_location: './recordings_epiphan'
  key: MEDIA_API_KEY
  secret: MEDIA_API_SECRET
  host: MEDIA_API_HOST
plugnmeet:
  host: PLUG_N_MEET_SERVER_DOMAIN
  key: PLUG_N_MEET_API_KEY
  secret: PLUG_N_MEET_SECRET
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""
  db: 0
opencast:
  host: OPENCAST_HOSTNAME
  username: OPENCAST_USERNAME
  password: OPENCAST_PASSWORD
mongodb:
  host: MONGODB_HOST
  database: MONGODB_DATABASE
  port: MONGODB_PORT