version: "3.9"
services:
  mongo:
    image: mongo:latest
    restart: always
  webapi:
    container_name: 'lbtu-media-api'
    restart: always
    build: .
    volumes:
      - ./recordings:/app/recording_files
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "9090:9090"