version: "3.9"
services:
  mongo:
    image: mongo:4.2.24-bionic
    restart: always
    networks:
      - app-intranet
  webapi:
    container_name: 'lbtu-media-api'
    restart: always
    build: .
    volumes:
      - ./recordings:/app/recording_files
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - app-intranet
    ports:
      - "8899:8899"
networks:
  app-intranet:
    driver: bridge