// @generated by protoc-gen-es v1.2.0 with parameter "target=ts,import_extension=.ts"
// @generated from file plugnmeet_recorder.proto (package plugnmeet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum plugnmeet.RecordingTasks
 */
export enum RecordingTasks {
  /**
   * @generated from enum value: START_RECORDING = 0;
   */
  START_RECORDING = 0,

  /**
   * @generated from enum value: STOP_RECORDING = 1;
   */
  STOP_RECORDING = 1,

  /**
   * @generated from enum value: START_RTMP = 2;
   */
  START_RTMP = 2,

  /**
   * @generated from enum value: STOP_RTMP = 3;
   */
  STOP_RTMP = 3,

  /**
   * @generated from enum value: END_RECORDING = 4;
   */
  END_RECORDING = 4,

  /**
   * @generated from enum value: END_RTMP = 5;
   */
  END_RTMP = 5,

  /**
   * @generated from enum value: RECORDING_PROCEEDED = 6;
   */
  RECORDING_PROCEEDED = 6,

  /**
   * @generated from enum value: STOP = 7;
   */
  STOP = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(RecordingTasks)
proto3.util.setEnumType(RecordingTasks, "plugnmeet.RecordingTasks", [
  { no: 0, name: "START_RECORDING" },
  { no: 1, name: "STOP_RECORDING" },
  { no: 2, name: "START_RTMP" },
  { no: 3, name: "STOP_RTMP" },
  { no: 4, name: "END_RECORDING" },
  { no: 5, name: "END_RTMP" },
  { no: 6, name: "RECORDING_PROCEEDED" },
  { no: 7, name: "STOP" },
]);

/**
 * @generated from enum plugnmeet.RecorderServiceType
 */
export enum RecorderServiceType {
  /**
   * @generated from enum value: RECORDING = 0;
   */
  RECORDING = 0,

  /**
   * @generated from enum value: RTMP = 1;
   */
  RTMP = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(RecorderServiceType)
proto3.util.setEnumType(RecorderServiceType, "plugnmeet.RecorderServiceType", [
  { no: 0, name: "RECORDING" },
  { no: 1, name: "RTMP" },
]);

/**
 * @generated from message plugnmeet.PlugNMeetToRecorder
 */
export class PlugNMeetToRecorder extends Message<PlugNMeetToRecorder> {
  /**
   * @generated from field: string from = 1;
   */
  from = "";

  /**
   * @generated from field: plugnmeet.RecordingTasks task = 2;
   */
  task = RecordingTasks.START_RECORDING;

  /**
   * @generated from field: string room_id = 3;
   */
  roomId = "";

  /**
   * @generated from field: string room_sid = 4;
   */
  roomSid = "";

  /**
   * @generated from field: string recording_id = 5;
   */
  recordingId = "";

  /**
   * @generated from field: string recorder_id = 6;
   */
  recorderId = "";

  /**
   * @generated from field: string access_token = 7;
   */
  accessToken = "";

  /**
   * @generated from field: optional string rtmp_url = 8;
   */
  rtmpUrl?: string;

  constructor(data?: PartialMessage<PlugNMeetToRecorder>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "plugnmeet.PlugNMeetToRecorder";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "task", kind: "enum", T: proto3.getEnumType(RecordingTasks) },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "room_sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "recording_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "recorder_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "rtmp_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlugNMeetToRecorder {
    return new PlugNMeetToRecorder().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlugNMeetToRecorder {
    return new PlugNMeetToRecorder().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlugNMeetToRecorder {
    return new PlugNMeetToRecorder().fromJsonString(jsonString, options);
  }

  static equals(a: PlugNMeetToRecorder | PlainMessage<PlugNMeetToRecorder> | undefined, b: PlugNMeetToRecorder | PlainMessage<PlugNMeetToRecorder> | undefined): boolean {
    return proto3.util.equals(PlugNMeetToRecorder, a, b);
  }
}

/**
 * @generated from message plugnmeet.RecorderToPlugNMeet
 */
export class RecorderToPlugNMeet extends Message<RecorderToPlugNMeet> {
  /**
   * @generated from field: string from = 1;
   */
  from = "";

  /**
   * @generated from field: plugnmeet.RecordingTasks task = 2;
   */
  task = RecordingTasks.START_RECORDING;

  /**
   * @generated from field: bool status = 3;
   */
  status = false;

  /**
   * @generated from field: string msg = 4;
   */
  msg = "";

  /**
   * @generated from field: string recording_id = 5;
   */
  recordingId = "";

  /**
   * @generated from field: string room_id = 6;
   */
  roomId = "";

  /**
   * @generated from field: string room_sid = 7;
   */
  roomSid = "";

  /**
   * @generated from field: string recorder_id = 8;
   */
  recorderId = "";

  /**
   * @generated from field: string file_path = 9;
   */
  filePath = "";

  /**
   * @generated from field: float file_size = 10;
   */
  fileSize = 0;

  constructor(data?: PartialMessage<RecorderToPlugNMeet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "plugnmeet.RecorderToPlugNMeet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "task", kind: "enum", T: proto3.getEnumType(RecordingTasks) },
    { no: 3, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "recording_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "room_sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "recorder_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "file_size", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecorderToPlugNMeet {
    return new RecorderToPlugNMeet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecorderToPlugNMeet {
    return new RecorderToPlugNMeet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecorderToPlugNMeet {
    return new RecorderToPlugNMeet().fromJsonString(jsonString, options);
  }

  static equals(a: RecorderToPlugNMeet | PlainMessage<RecorderToPlugNMeet> | undefined, b: RecorderToPlugNMeet | PlainMessage<RecorderToPlugNMeet> | undefined): boolean {
    return proto3.util.equals(RecorderToPlugNMeet, a, b);
  }
}

