export const EPIPHAN_SERVICE = 'EPIPHAN_SERVICE';
export const PLUGNMEET_SERVICE = 'PLUGNMEET_SERVICE';
export const OPENCAST_SERVICE = 'OPENCAST_SERVICE';
export const LIVEKIT_INGRESS_SERVICE = 'LIVEKIT_INGRESS_SERVICE';
export const LIVEKIT_EGRESS_SERVICE = 'LIVEKIT_EGRESS_SERVICE';

// Redis keys
export const PLUGNMEET_RECORDER_INFO_KEY = 'pnm:recorders';